# Generated by Django 3.2.5 on 2021-08-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210807_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='asked_questions',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='solved_questions',
        ),
    ]
