# Generated by Django 3.2.5 on 2021-08-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0001_initial'),
        ('profiles', '0004_auto_20210807_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='asked_questions',
            field=models.ManyToManyField(blank=True, to='q_and_a.Question'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='solved_questions',
            field=models.ManyToManyField(blank=True, to='q_and_a.Answer'),
        ),
    ]
