# Generated by Django 3.2.5 on 2021-08-07 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0001_initial'),
        ('profiles', '0005_auto_20210807_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='asked_questions',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='solved_questions',
        ),
        migrations.AddField(
            model_name='profile',
            name='answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='q_and_a.answer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='q_and_a.question'),
        ),
    ]
