# Generated by Django 3.2.5 on 2021-07-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
