# Generated by Django 3.2.5 on 2021-07-26 11:48

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
