# Generated by Django 3.2.5 on 2021-07-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
