# Generated by Django 3.2.5 on 2021-07-29 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210729_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply',
        ),
        migrations.AddField(
            model_name='reply',
            name='comment_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comments'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
