# Generated by Django 3.2.5 on 2021-07-30 10:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='turorial',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
