# Generated by Django 3.2.5 on 2021-07-30 10:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_alter_tutorial_turorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='turorial',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
