# Generated by Django 3.2.5 on 2021-08-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_tutorial_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tutorials'),
        ),
    ]
