# Generated by Django 3.2.5 on 2021-08-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_tutorial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='basic_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
