# Generated by Django 3.2.5 on 2021-07-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_alter_tutorial_turorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tut_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
