# Generated by Django 3.2.5 on 2021-08-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_tutorial_basic_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='basic_desc',
            new_name='Tutorial',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='desc',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='About',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
