# Generated by Django 3.2.5 on 2021-08-08 15:26

from django.db import migrations, models
import django.utils.timezone
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_auto_20210808_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Tutorial',
            field=froala_editor.fields.FroalaField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
