# Generated by Django 3.2.5 on 2021-07-31 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_tutorial_tut_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='turorial',
            new_name='description',
        ),
    ]
