# Generated by Django 3.2.5 on 2021-08-18 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=45000)),
                ('desc', models.TextField(blank=True, null=True)),
                ('challenge_question', froala_editor.fields.FroalaField()),
                ('sample_input', models.CharField(blank=True, default='', max_length=45000, null=True)),
                ('sample_output', models.CharField(blank=True, default='', max_length=45000, null=True)),
                ('test_case1', models.CharField(blank=True, max_length=1000, null=True)),
                ('test_case2', models.CharField(blank=True, max_length=1000, null=True)),
                ('test_case1_sol', models.CharField(blank=True, max_length=1010, null=True)),
                ('test_case2_sol', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolvedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenges', models.ManyToManyField(related_name='solved_challenges', to='challenges.ChallengeQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='challengequestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challengetopic'),
        ),
        migrations.AddField(
            model_name='challengequestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
