# Generated by Django 3.2.5 on 2021-08-13 20:12

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('challenge_question', froala_editor.fields.FroalaField()),
                ('input_value', models.CharField(max_length=25)),
                ('test_case', models.CharField(max_length=25)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challengetopic')),
            ],
        ),
    ]
