# Generated by Django 3.2.5 on 2021-08-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengequestion',
            name='qno',
        ),
        migrations.RemoveField(
            model_name='challengequestion',
            name='test_case2',
        ),
        migrations.RemoveField(
            model_name='challengequestion',
            name='test_case2_sol',
        ),
    ]
