# Generated by Django 3.2.5 on 2021-08-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=45000)),
                ('test_case_no', models.IntegerField(default=0)),
                ('sample_input', models.CharField(default='', max_length=45000)),
                ('sample_output', models.CharField(default='', max_length=45000)),
                ('test_case1', models.CharField(max_length=1000)),
                ('test_case2', models.CharField(max_length=1000)),
                ('test_case3', models.CharField(max_length=1000)),
                ('test_case1_sol', models.CharField(max_length=1000)),
                ('test_case3_sol', models.CharField(max_length=1000)),
            ],
        ),
    ]
