# Generated by Django 3.2.5 on 2021-08-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20210819_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengequestion',
            name='user',
        ),
    ]
