# Generated by Django 3.2.5 on 2021-08-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_solved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solved',
            old_name='solved',
            new_name='sol',
        ),
    ]
