# Generated by Django 3.2.5 on 2021-08-23 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_rename_solved_solved_sol'),
    ]

    operations = [
        migrations.AddField(
            model_name='solved',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solved',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
