# Generated by Django 3.2.5 on 2021-08-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_auto_20210823_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='solved',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
