# Generated by Django 3.2.5 on 2021-08-07 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('q_and_a', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='upvote',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
