# Generated by Django 3.2.5 on 2021-08-09 15:59

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0003_answer_downvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samp', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
