# Generated by Django 3.2.5 on 2021-07-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0004_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
    ]
