# Generated by Django 3.2.5 on 2021-08-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0004_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
    ]
