# Generated by Django 3.2.5 on 2021-08-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0006_auto_20210810_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
