# Generated by Django 3.2.5 on 2021-08-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0007_question_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
