# Generated by Django 3.2.5 on 2021-07-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0008_alter_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
