# Generated by Django 3.2.5 on 2021-08-23 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('q_and_a', '0010_question_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='view_count',
        ),
        migrations.AddField(
            model_name='question',
            name='view_count',
            field=models.ManyToManyField(related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
