# Generated by Django 3.2.5 on 2021-07-26 17:34

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0010_auto_20210724_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
