# Generated by Django 3.2.5 on 2021-08-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0011_auto_20210823_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
