# Generated by Django 3.2.5 on 2021-07-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0011_alter_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='attachment',
        ),
    ]
