# Generated by Django 3.2.5 on 2021-07-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0012_remove_question_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_solved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
