# Generated by Django 3.2.5 on 2021-07-27 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0013_answer_is_solved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='q_and_a.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='q_and_a.question')),
            ],
        ),
    ]
