# Generated by Django 3.2.5 on 2021-07-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0014_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='tags',
            field=models.ManyToManyField(to='q_and_a.Tags'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='q_and_a.Tags'),
        ),
    ]
