# Generated by Django 3.2.5 on 2021-07-27 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('q_and_a', '0016_alter_question_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('asked_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='q_and_a.answer')),
                ('solved_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='q_and_a.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
