# Generated by Django 3.2.5 on 2021-07-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0018_auto_20210727_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointstable',
            name='asked_questions',
        ),
        migrations.AddField(
            model_name='pointstable',
            name='asked_questions',
            field=models.ManyToManyField(blank=True, null=True, to='q_and_a.Answer'),
        ),
        migrations.RemoveField(
            model_name='pointstable',
            name='solved_questions',
        ),
        migrations.AddField(
            model_name='pointstable',
            name='solved_questions',
            field=models.ManyToManyField(blank=True, null=True, to='q_and_a.Question'),
        ),
    ]
