# Generated by Django 3.2.5 on 2021-07-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0021_alter_pointstable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_solved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
