# Generated by Django 3.2.5 on 2021-07-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0022_alter_answer_is_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
