# Generated by Django 3.2.5 on 2021-07-28 09:44

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0023_alter_answer_is_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
