# Generated by Django 3.2.5 on 2021-07-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0024_auto_20210728_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
